In [20]:
import os
import pandas as pd
from googleapiclient.discovery import build

API_VERSION = 'v3'

youtube = build('youtube', API_VERSION, developerKey="AIzaSyAAqy6a-to5YTdw0PgKjqeHtvnyPsq-o24")

In [38]:
def get_channel_stats(youtube, channel_id):
    request = youtube.channels().list(
        part='snippet, statistics',
        id=channel_id)
    response = request.execute()

    data = dict(channel_name=response['items'][0]['snippet']['title'],
                total_subscribers=response['items'][0]['statistics']['subscriberCount'],
                total_views=response['items'][0]['statistics']['viewCount'],
                total_videos=response['items'][0]['statistics']['videoCount'])
    return data



# channel_id = "UC_aEa8K-EOJ3D6gOs7HcyNg" 
channel_id = "UC9LQwHZoucFT94I2h6JOcjw"
get_channel_stats(youtube, channel_id)

{'channel_name': 'Liverpool FC',
 'total_subscribers': '10100000',
 'total_views': '2792324858',
 'total_videos': '6603'}

In [31]:
# Read CSV into dataframe 
df = pd.read_csv("youtube_data_united-states.csv")


# Extract channel IDs and remove potential duplicates
channel_ids = df['NAME'].str.split('@').str[-1].unique()


# Initialize a list to keep track of channel stats
channel_stats = []

In [40]:
# Loop over the channel IDs and get stats for each
for ids in channel_ids:
    stats = get_channel_stats(youtube, channel_id)
    channel_stats.append(stats)

In [43]:

# Convert the list of stats to a df
stats_df = pd.DataFrame(channel_stats)


df.reset_index(drop=True, inplace=True)
stats_df.reset_index(drop=True, inplace=True)


# Concatenate the dataframes horizontally
combined_df = pd.concat([df, stats_df], axis=1)


# Drop the 'channel_name' column from stats_df (since 'NOMBRE' already exists)
# combined_df.drop('channel_name', axis=1, inplace=True)


# Save the merged dataframe back into a CSV file
combined_df.to_csv('updated_youtube_data_united-states.csv', index=False)


combined_df.head(10)

,#,NAME,FOLLOWERS,ER,COUNTRY,TOPIC OF INFLUENCE,POTENTIAL REACH,channel_name,total_subscribers,total_views,total_videos
0,1.0,T-Series @UCq-Fj5jknLsUf-MWSy4_brA,234M,-,India,NaN,70.2M,T-Series,268000000,258896707763,21258
1,2.0,Cocomelon - Nursery Rhymes @UCbCmjCuTUZos6Inko...,144M,-,United States,NaN,43.2M,Cocomelon - Nursery Rhymes,177000000,182880824642,1191
2,3.0,SET India @UCpEhnqL0y41EpW2TvWAHD7Q,139M,-,India,NaN,41.7M,SET India,174000000,165576494578,140014
3,4.0,PewDiePie @UC-lHJZR3Gqxm24_Vd_AJ5Yw,111M,0.1%,United States,NaN,33.3M,PewDiePie,111000000,29326445869,4768
4,5.0,MrBeast @UCX6OQ3DkcsbYNE6H8uQQuVA,100M,2.4%,United States,Celebrity Pets,30M,MrBeast,289000000,52914130783,803
5,6.0,Like Nastya @UCJplp5SjeGSdVdwsfb9Q7lQ,97.3M,-,United States,NaN,29.2M,Like Nastya,116000000,101482418890,886
6,7.0,✿ Kids Diana Show @UCk8GzjMOrta8yxDcKfylJYw,94.2M,-,NaN,NaN,28.3M,✿ Kids Diana Show,123000000,104005581412,1230
7,8.0,Zee Music Company @UCFFbwnve3yF62-tVXkTyHqg,91.4M,-,India,NaN,27.4M,Zee Music Company,108000000,67294949146,11407
8,9.0,WWE @UCJ5v_MCY6GNUBTO8-D3XoAg,91.2M,-,NaN,NaN,27.4M,WWE,102000000,85494986135,77120
9,10.0,Vlad and Niki @UCvlE5gTbOvjiolFlEm-c_Ow,84.3M,-,United States,Marketing and Advertising Music,25.3M,Vlad and Niki,120000000,91721203361,730